services:
  react:
    image: frontend_image
    ports:
      - "3000:3000"
  user-demo:
    image: user_img
    ports:
      - "8080:8080"
  mysql_user:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: User

  device-manager:
    image: device_img
    ports:
      - "8081:8081"
  mysql_device:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Branzapute73!
      MYSQL_DATABASE: Device
